### ISSUE TITLE
..

### ISSUE THREAD

**Issue by lcd111** [vkhoi/Super-Resolution-PyTorch#1]
When I tested an image, I found the restored HR image was darker than the real HR image. They look completely different.Please help me if you have time

**Comment by vkhoi** [comment]
Can you give me a link to your image? And what model did you test on (SRCNN, ESPCN, or FRSCNN)? Does this happen to all images you test or does it only happen to one specific image?

**Comment by lcd111** [comment]
First of all, thank you for your reply. I know what my problem is. I made some changes to the model, so the resulting image is a bit of a problem. I just adjusted some more models, and this time the image works. Thank you very much.i used espcn

**Comment by vkhoi** [comment]
Great to hear that. If you encounter any problem with the code, feel free to open another issue.
